645. Set Mismatch
Solved
Easy
Topics
Companies
You have a set of integers s, which originally contains all the numbers from 1 to n. Unfortunately, due to some error, one of the numbers in s got duplicated to another number in the set, which results in repetition of one number and loss of another number.

You are given an integer array nums representing the data status of this set after the error.

Find the number that occurs twice and the number that is missing and return them in the form of an array.

 

Example 1:

Input: nums = [1,2,2,4]
Output: [2,3]
Example 2:

Input: nums = [1,1]
Output: [1,2]
 

Constraints:

2 <= nums.length <= 104
1 <= nums[i] <= 104

Seen this question in a real interview before?
1/5
Yes
No
Accepted
452.4K
Submissions
1M
Acceptance Rate
44.5%
Topics
Companies
Similar Questions
Discussion (125)

1)Using HashMap:
class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        dict = {}

        for i in range(1,len(nums)+1):
            dict[i] = 0

        for num in nums:
            dict[num] = dict[num] + 1

        ans = []
        for i in range(1,len(nums)+1):
            if dict[i] == 2:
                ans.append(i)
                break

        for i in range(1,len(nums)+1):
            if dict[i] == 0:
                ans.append(i)
                break

        return ans 

2)BruteForce Approach:
class Solution {
public:
    vector<int> findErrorNums(vector<int>& nums) {
        vector <int> ans;
        for(int i=0;i<nums.size();i++){
            for(int j=i+1;j<nums.size();j++){
                if(nums[i] == nums[j]){
                    ans.push_back(nums[i]);
                }
            }
        }

        int flag = 0;
        for(int i=1;i<=nums.size();i++){
            for(int j=0;j<nums.size();j++){
                if(i==nums[j]){
                    flag = 1;
                }
            }
            if(flag == 0){
                ans.push_back(i);
                break;
            }
            flag = 0;
        }
        return ans;
    }
};

3)By Extra List append:
class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        ans =[]
        without_dup = []
        for item in nums:
            if item not in without_dup:
                without_dup.append(item)
            else:
                ans.append(item)
        
        for i in range(1,len(nums)+1):
            if i not in without_dup:
                ans.append(i)

        return ans

4)Using Sorting:

Sort the array in ascending order to make it easier to identify the duplicate and missing numbers.
Sort the array in ascending order to make it easier to identify the duplicate and missing numbers.
If the duplicate is equal to the current index + 1, it means it's the duplicate causing the error. The missing number is the next index.
If the duplicate is not equal to the current index + 1, it means it's the missing number causing the error. The duplicate is the number at the previous index.
Return the found duplicate and missing numbers.

#include <vector>
#include <algorithm>

class Solution {
public:
    std::vector<int> findErrorNums(std::vector<int>& nums) {
        std::sort(nums.begin(), nums.end());
        std::vector<int> er(2, 0);
        int i = 0;

        while (i < nums.size()) {
            if (nums[i] == nums[i + 1]) {
                if (nums[i] == i + 1) {
                    er[0] = nums[i];
                    i += 1;
                    while (i < nums.size() && nums[i] == i) {
                        i += 1;
                    }
                    er[1] = i;
                    break;
                } else {
                    er[0] = nums[i];
                    while (i > -1 && nums[i] != i + 1) {
                        i -= 1;
                    }
                    if (i < 0) {
                        er[1] = 1;
                    } else {
                        er[1] = i + 2;
                    }
                    break;
                }
            }
            i += 1;
        }

        return er;
    }
};